name: Run Python Scrapers

on:
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10:00 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Ensure the workflow has write permissions

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This action will use Node.js 20 automatically

    - name: Set up Python
      uses: actions/setup-python@v4  # This action will use Node.js 20 automatically
      with:
        python-version: '3.11'  # Using the latest stable version of Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt  # Adjusted path to requirements.txt

    - name: Run aggregator script
      run: python aggregate_scrapers.py
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add public/news_data2.json
        git commit -m "Update scraped data"
        git push origin Deployment  # Ensure changes are pushed to the Deployment branch
